# Copyright (c) 2022-2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

extra:
  context: !ENV [CONTEXT, "production"]
  deploy: !ENV DEPLOY_ID
  social:
    - icon: simple/mastodon
      link: https://mastodon.neat.computer/@privacyguides
      name: Mastodon
    - icon: simple/matrix
      link: https://matrix.to/#/#privacyguides:matrix.org
      name: Matrix
    - icon: simple/discourse
      link: https://discuss.privacyguides.net/
      name: Forum
    - icon: simple/github
      link: https://github.com/privacyguides
      name: GitHub
    - icon: simple/torbrowser
      link: http://www.xoe4vn5uwdztif6goazfbmogh6wh5jc4up35bqdflu6bkdc5cas5vjqd.onion/
      name: Hidden service
  alternate:
    - name: English
      link: /en/
      lang: en
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1fa-1f1f8.svg
    - name: Español
      link: /es/
      lang: es
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1ea-1f1f8.svg
    - name: Français
      link: /fr/
      lang: fr
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1eb-1f1f7.svg
    - name: עִברִית
      link: /he/
      lang: he
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1ee-1f1f1.svg
    - name: Italian
      link: /it/
      lang: it
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1ee-1f1f9.svg
    - name: Nederlands
      link: /nl/
      lang: nl
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1f3-1f1f1.svg
    - name: 正體中文
      link: /zh-hant/
      lang: zh-Hant
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1ed-1f1f0.svg
    - name: Russian
      link: /ru/
      lang: ru
      icon: https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1f7-1f1fa.svg

repo_url: https://github.com/privacyguides/privacyguides.org
repo_name: ""

theme:
  name: material
  custom_dir: ../theme
  logo: ../../theme/assets/brand/SVG/Logo/privacy-guides-logo-notext-colorbg.svg
  favicon: assets/brand/png/favicon/favicon-32x32.png
  icon:
    repo: simple/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - search.highlight

extra_css:
  - assets/stylesheets/extra.css?v=3.2.0
extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/feedback.js

watch:
  - ../theme
  - ../includes
  - mkdocs-common.yml

plugins:
  tags: {}
  search: {}
  macros: {}
  meta: {}
  git-committers:
    enabled: !ENV [NETLIFY, false]
    repository: privacyguides/privacyguides.org
    branch: main
  git-revision-date-localized:
    enabled: !ENV [NETLIFY, false]
    exclude:
      - index.md
    fallback_to_build_date: true
  privacy:
    assets_exclude:
      - cdn.jsdelivr.net/npm/mathjax@3/*
      - api.privacyguides.net/*
  optimize:
    enabled: !ENV [NETLIFY, false]
  typeset: {}
  social:
    cards: !ENV [CARDS, true]
    cards_dir: assets/img/social
    cards_layout_dir: config/layouts
    cards_layout: page
    # cards_layout: pride

markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.arithmatex:
    generic: true
  pymdownx.critic: {}
  pymdownx.caret: {}
  pymdownx.keys: {}
  pymdownx.mark: {}
  pymdownx.tilde: {}
  pymdownx.snippets: {}
  pymdownx.tasklist:
    custom_checkbox: true
  attr_list: {}
  def_list: {}
  md_in_html: {}
  meta: {}
  abbr: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  tables: {}
  footnotes: {}
  toc:
    permalink: true
    toc_depth: 4

nav:
  - Home: 'index.md'
  - Knowledge Base:
    - 'basics/why-privacy-matters.md'
    - 'basics/threat-modeling.md'
    - 'basics/common-threats.md'
    - 'basics/common-misconceptions.md'
    - 'basics/account-creation.md'
    - 'basics/account-deletion.md'
    - Technology Essentials:
      - 'basics/passwords-overview.md'
      - 'basics/multi-factor-authentication.md'
      - 'basics/hardware.md'
      - 'basics/email-security.md'
      - 'basics/vpn-overview.md'
    - Advanced Topics:
      - 'advanced/dns-overview.md'
      - 'advanced/tor-overview.md'
      - 'advanced/payments.md'
      - 'advanced/communication-network-types.md'
    - Operating Systems:
      - 'os/android-overview.md'
      - 'os/ios-overview.md'
      - 'os/linux-overview.md'
      - 'os/macos-overview.md'
      - 'os/qubes-overview.md'
    - kb-archive.md
  - Recommendations:
    - 'tools.md'
    - Internet Browsing:
      - 'tor.md'
      - 'desktop-browsers.md'
      - 'mobile-browsers.md'
    - Providers:
      - 'cloud.md'
      - 'dns.md'
      - 'email.md'
      - 'financial-services.md'
      - 'search-engines.md'
      - 'vpn.md'
    - Software:
      - 'calendar.md'
      - 'cryptocurrency.md'
      - 'data-redaction.md'
      - 'email-clients.md'
      - 'encryption.md'
      - 'file-sharing.md'
      - 'frontends.md'
      - 'multi-factor-authentication.md'
      - 'news-aggregators.md'
      - 'notebooks.md'
      - 'passwords.md'
      - 'productivity.md'
      - 'real-time-communication.md'
    - Operating Systems:
      - 'android.md'
      - 'desktop.md'
      - 'router.md'
  - About:
    - 'about/index.md'
    - 'about/criteria.md'
    - 'about/statistics.md'
    - 'about/notices.md'
    - 'about/privacy-policy.md'
    - Community:
      - 'about/donate.md'
      - Online Services: 'about/services.md'
      - Code of Conduct: 'CODE_OF_CONDUCT.md'
      - 'about/privacytools.md'
    - Contributing:
      - Writing Guide:
        - 'meta/writing-style.md'
        - 'meta/brand.md'
        - 'meta/translations.md'
      - Technical Guides:
        - 'meta/uploading-images.md'
        - 'meta/git-recommendations.md'
  - Changelog: 'https://github.com/privacyguides/privacyguides.org/releases'
  - Forum: 'https://discuss.privacyguides.net/'
  - Blog: 'https://blog.privacyguides.org/'
